# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
User.destroy_all
Song.destroy_all

demo_user = User.create({username: "GlasgowFan65", email: "iloveshoegaze@gmail.com", password: "shoegaze"})

artist1 = User.create({username: "My Bloody Valentine", email: "iloveshoegaze@gmail.com", password: "shoegaze"})
artist2 = User.create({username: "Slowdive", email: "slowdive@gmail.com", password: "shoegaze"})
artist3 = User.create({username: "Ride", email: "ride@gmail.com", password: "shoegaze"})
artist4 = User.create({username: "The Jesus & Mary Chain", email: "jesusandmarychain@gmail.com", password: "shoegaze"})
artist5 = User.create({username: "Alcest", email: "alcest@gmail.com", password: "shoegaze"})
artist6 = User.create({username: "Nothing", email: "nothing@gmail.com", password: "shoegaze"})
artist7 = User.create({username: "The Raveonettes", email: "theraveonettes@gmail.com", password: "shoegaze"})
artist8 = User.create({username: "The Brian Jonestown Massacre", email: "thebrianjonestownmassacre@gmail.com", password: "shoegaze"})
artist9 = User.create({username: "The Cure", email: "thecure@gmail.com", password: "shoegaze"})


Loveless1 = Song.create({title: "Only Shallow", album: "Loveless", genre: "shoegaze", user_id: artist1.id})
Loveless2 = Song.create({title: "Loomer", album: "Loveless", genre: "shoegaze", user_id: artist1.id})
Loveless3 = Song.create({title: "Touched", album: "Loveless", genre: "shoegaze", user_id: artist1.id})
Loveless4 = Song.create({title: "To Here Knows When", album: "Loveless", genre: "shoegaze", user_id: artist1.id})
Loveless5 = Song.create({title: "When You Sleep", album: "Loveless", genre: "shoegaze", user_id: artist1.id})
Loveless6 = Song.create({title: "I Only Said", album: "Loveless", genre: "shoegaze", user_id: artist1.id})
Loveless7 = Song.create({title: "Come In Alone", album: "Loveless", genre: "shoegaze", user_id: artist1.id})
Loveless8 = Song.create({title: "Sometimes", album: "Loveless", genre: "shoegaze", user_id: artist1.id})
Loveless9 = Song.create({title: "Blown A Wish", album: "Loveless", genre: "shoegaze", user_id: artist1.id})
Loveless10 = Song.create({title: "What You Want", album: "Loveless", genre: "shoegaze", user_id: artist1.id})
Loveless11 = Song.create({title: "Soon", album: "Loveless", genre: "shoegaze", user_id: artist1.id})

Souvlaki1 = Song.create({title: "Alison", album: "Souvlaki", genre: "shoegaze", user_id: artist2.id})
Souvlaki2 = Song.create({title: "Machine Gun", album: "Souvlaki", genre: "shoegaze", user_id: artist2.id})
Souvlaki3 = Song.create({title: "40 Days", album: "Souvlaki", genre: "shoegaze", user_id: artist2.id})
Souvlaki4 = Song.create({title: "Sing", album: "Souvlaki", genre: "shoegaze", user_id: artist2.id})
Souvlaki5 = Song.create({title: "Here She Comes", album: "Souvlaki", genre: "shoegaze", user_id: artist2.id})
Souvlaki6 = Song.create({title: "Souvlaki Space Station", album: "Souvlaki", genre: "shoegaze", user_id: artist2.id})
Souvlaki7 = Song.create({title: "When The Sun Hits", album: "Souvlaki", genre: "shoegaze", user_id: artist2.id})
Souvlaki8 = Song.create({title: "Altogether", album: "Souvlaki", genre: "shoegaze", user_id: artist2.id})
Souvlaki9 = Song.create({title: "Melon Yellow", album: "Souvlaki", genre: "shoegaze", user_id: artist2.id})
Souvlaki10 = Song.create({title: "Dagger", album: "Souvlaki", genre: "shoegaze", user_id: artist2.id})

Nowhere1 = Song.create({title: "Seagull", album: "Nowhere", genre: "shoegaze", user_id: artist3.id})
Nowhere2 = Song.create({title: "Kaleidoscope", album: "Nowhere", genre: "shoegaze", user_id: artist3.id})
Nowhere3 = Song.create({title: "In A Different Place", album: "Nowhere", genre: "shoegaze", user_id: artist3.id})
Nowhere4 = Song.create({title: "Polar Bear", album: "Nowhere", genre: "shoegaze", user_id: artist3.id})
Nowhere5 = Song.create({title: "Dreams Burn Down", album: "Nowhere", genre: "shoegaze", user_id: artist3.id})
Nowhere6 = Song.create({title: "Decay", album: "Nowhere", genre: "shoegaze", user_id: artist3.id})
Nowhere7 = Song.create({title: "Paralysed", album: "Nowhere", genre: "shoegaze", user_id: artist3.id})
Nowhere8 = Song.create({title: "Vapour Trail", album: "Nowhere", genre: "shoegaze", user_id: artist3.id})
Nowhere9 = Song.create({title: "Taste", album: "Nowhere", genre: "shoegaze", user_id: artist3.id})
Nowhere10 = Song.create({title: "Here And Now", album: "Nowhere", genre: "shoegaze", user_id: artist3.id})
Nowhere11 = Song.create({title: "Nowhere", album: "Nowhere", genre: "shoegaze", user_id: artist3.id})

Psychocandy1 = Song.create({title: "Just Like Honey", album: "Psychocandy", genre: "shoegaze", user_id: artist4.id})
Psychocandy2 = Song.create({title: "The Living End", album: "Psychocandy", genre: "shoegaze", user_id: artist4.id})
Psychocandy3 = Song.create({title: "Taste The Floor", album: "Psychocandy", genre: "shoegaze", user_id: artist4.id})
Psychocandy4 = Song.create({title: "The Hardest Walk", album: "Psychocandy", genre: "shoegaze", user_id: artist4.id})
Psychocandy5 = Song.create({title: "Cut Dead", album: "Psychocandy", genre: "shoegaze", user_id: artist4.id})
Psychocandy6 = Song.create({title: "In A Hole", album: "Psychocandy", genre: "shoegaze", user_id: artist4.id})
Psychocandy7 = Song.create({title: "Taste Of Cindy", album: "Psychocandy", genre: "shoegaze", user_id: artist4.id})
Psychocandy8 = Song.create({title: "Some Candy Talking", album: "Psychocandy", genre: "shoegaze", user_id: artist4.id})
Psychocandy9 = Song.create({title: "Never Understand", album: "Psychocandy", genre: "shoegaze", user_id: artist4.id})
Psychocandy10 = Song.create({title: "Inside Me", album: "Psychocandy", genre: "shoegaze", user_id: artist4.id})
Psychocandy11 = Song.create({title: "Sowing Seeds", album: "Psychocandy", genre: "shoegaze", user_id: artist4.id})
Psychocandy12 = Song.create({title: "My Little Underground", album: "Psychocandy", genre: "shoegaze", user_id: artist4.id})
Psychocandy13 = Song.create({title: "You Trip Me Up", album: "Psychocandy", genre: "shoegaze", user_id: artist4.id})
Psychocandy14 = Song.create({title: "Something's Wrong", album: "Psychocandy", genre: "shoegaze", user_id: artist4.id})
Psychocandy15 = Song.create({title: "It's So Hard", album: "Psychocandy", genre: "shoegaze", user_id: artist4.id})

LesVoyagesDeLame1 = Song.create({title: "Autre Temps" album: "Les Voyages De Lame", genre: "Shoegaze/Post-Black Metal", user_id: artist5.id})
LesVoyagesDeLame1 = Song.create({title: "Autre Temps" album: "Les Voyages De Lame", genre: "Shoegaze/Post-Black Metal", user_id: artist5.id})
LesVoyagesDeLame1 = Song.create({title: "Autre Temps" album: "Les Voyages De Lame", genre: "Shoegaze/Post-Black Metal", user_id: artist5.id})
LesVoyagesDeLame1 = Song.create({title: "Autre Temps" album: "Les Voyages De Lame", genre: "Shoegaze/Post-Black Metal", user_id: artist5.id})
LesVoyagesDeLame1 = Song.create({title: "Autre Temps" album: "Les Voyages De Lame", genre: "Shoegaze/Post-Black Metal", user_id: artist5.id})
LesVoyagesDeLame1 = Song.create({title: "Autre Temps" album: "Les Voyages De Lame", genre: "Shoegaze/Post-Black Metal", user_id: artist5.id})
LesVoyagesDeLame1 = Song.create({title: "Autre Temps" album: "Les Voyages De Lame", genre: "Shoegaze/Post-Black Metal", user_id: artist5.id})
LesVoyagesDeLame1 = Song.create({title: "Autre Temps" album: "Les Voyages De Lame", genre: "Shoegaze/Post-Black Metal", user_id: artist5.id})
LesVoyagesDeLame1 = Song.create({title: "Autre Temps" album: "Les Voyages De Lame", genre: "Shoegaze/Post-Black Metal", user_id: artist5.id})